version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always